---
- name: Install kubectl, kubeadm, kubelet 
  hosts: all
  become: true
  tasks:
  - name: Install prerequisites
    ansible.builtin.apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
      state: present
      update_cache: yes

  - name: Add Kubernetes apt key
    ansible.builtin.shell: "curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg"
    ignore_errors: true
  - name: Add Kubernetes apt key
    ansible.builtin.shell: 'echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list'
    ignore_errors: true
  # - name: Add Kubernetes apt repository
  #   ansible.builtin.apt_repository:
  #     repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main'
  #     state: present
  #     filename: kubernetes.list

  - name: Install kubelet, kubeadm, and kubectl
    ansible.builtin.apt:
      name:
      - kubelet={{ kubelet_version }}
      - kubeadm={{ kubeadm_version }}
      - kubectl={{ kubectl_version }}
      state: present
      update_cache: true

  - name: Pin the version of kubeadm
    ansible.builtin.dpkg_selections:
      name: kubeadm
      selection: hold
      
  - name: Pin the version of kubectl
    ansible.builtin.dpkg_selections:
      name: kubectl
      selection: hold

  - name: Pin the version of kubectl
    ansible.builtin.dpkg_selections:
      name: kubectl
      selection: hold
      
  - name: Set node IP address for kubelet
    ansible.builtin.lineinfile:
      path: /etc/default/kubelet
      line: 'KUBELET_EXTRA_ARGS=--node-ip={{ ansible_default_ipv4.address }}'
      create: true