---
- name: Install Containerd
  hosts: all
  become: true

  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Create keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /tmp/docker.gpg

    - name: Import Docker GPG key
      ansible.builtin.command: gpg --dearmor -o /etc/apt/keyrings/docker.gpg /tmp/docker.gpg

    - name: Set permissions for Docker GPG key
      ansible.builtin.shell: echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes
    
    - name: Install containerd.io and related packages
      ansible.builtin.apt:
        name:
          - containerd.io
        state: present
    
    - name: Configure containerd
      ansible.builtin.copy:
        src: ../config.toml
        dest: /etc/containerd/config.toml
        force: yes

    # - name: Restart containerd
    #   ansible.builtin.systemd:
    #     name: containerd
    #     state: restarted

    - name: Enable and start containerd service
      become: true
      ansible.builtin.systemd:
        daemon_reload: true
        state: restarted
        enabled: true 
        name: containerd